import Head from "next/head";

import { Inter } from "@next/font/google";
import Navbar from "./Navbar";
import Hero from "./Hero";
import SecondComponent from "./SecondComponent";
import ThirdComponent from "./ThirdComponent";
import ResumeComponent from "./ResumeComponent";
import TemplateComponent from "./TemplateComponent";
import PortFolioMaker from "./PortFolioMaker";
import HowTo from "./HowTo";
import Facts from "./Facts";
import Footer from "./Footer";
import SplashScreen from "./SplashScreen";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const router = useRouter();
  const [showComponent, setShowComponent] = useState(true);
  useEffect(() => {
    let timer;
    if (showComponent) {
      timer = setTimeout(() => {
        setShowComponent(false);
      }, 4000); // change the value (in milliseconds) to adjust the time
    }
    return () => clearTimeout(timer);
  });
  useEffect(() => {
    if (
      typeof window !== "undefined" &&
      localStorage.getItem("userid") !== null
    ) {
      router.replace("/TemplatePage");
    }
  }, []);
  return (
    <>
      <Head>
        <title>PROFILE MATE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://cdn-icons-png.flaticon.com/128/3135/3135731.png"
        />
      </Head>

      {showComponent ? (
        <SplashScreen />
      ) : (
        <>
          <Navbar />

          <Hero />
          <SecondComponent />
          <ThirdComponent />
          <ResumeComponent />
          <TemplateComponent />
          <PortFolioMaker />
          <HowTo />
          <Facts />
          <Footer />
        </>
      )}
    </>
  );
}
